import { mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { dirname, join, normalize, resolve, sep } from "node:path";
import { checksumOf, type PutResult, type StorageDriver } from "@/lib/storage/provider";

export * from "@/lib/storage/provider";

/**
 * Driver selection, and the local-disk driver.
 *
 * `STORAGE_DRIVER` picks one; `local` is the default because it is the only one
 * that works with no configuration, and a deployment that has not thought about
 * storage should get something that functions rather than an error on the first
 * upload.
 *
 * The driver is resolved per call, never cached in a module variable — the same
 * rule the AI providers follow for their keys, and for the same reason: a
 * long-lived server would otherwise keep using the driver that was configured
 * when it booted.
 */

// ── Local disk ────────────────────────────────────────────────────────────

/**
 * Files on the server's own filesystem.
 *
 * Good for a single-server deployment and for development; wrong for anything
 * horizontally scaled or serverless, where the disk is neither shared nor
 * durable. That is a real limitation and is documented rather than papered
 * over — the answer is `STORAGE_DRIVER=s3`, not a cleverer local driver.
 *
 * The root defaults to `.uploads` at the project root and is deliberately
 * **not** inside `public/`: anything under `public/` is served by the framework
 * with no authorisation at all, which would hand every submission to anyone who
 * could guess a filename and make §67 unenforceable.
 */
class LocalDriver implements StorageDriver {
  readonly name = "local";

  private root(): string {
    return resolve(process.env.STORAGE_LOCAL_ROOT?.trim() || ".uploads");
  }

  isConfigured(): boolean {
    return true;
  }

  /**
   * Resolve a key to a path, refusing anything that escapes the root.
   *
   * Keys are generated by `buildStorageKey` and contain no user input, so this
   * is defence against a *future* caller rather than against today's — which
   * is exactly when a traversal check is worth having, because the caller that
   * introduces the bug will not be thinking about it.
   */
  private pathFor(key: string): string {
    const root = this.root();
    const full = resolve(join(root, normalize(key)));

    if (full !== root && !full.startsWith(root + sep)) {
      throw new Error("storage key escapes the storage root");
    }

    return full;
  }

  async put(key: string, bytes: Uint8Array, contentType: string): Promise<PutResult> {
    /**
     * The content type is part of the interface and has nowhere to go here: a
     * filesystem stores bytes and a name, not a MIME type. It is kept on the
     * `StoredFile` row instead, which is what the download route reads — so
     * the local driver and an S3 driver serve the same header from the same
     * source, rather than one of them trusting object metadata.
     */
    void contentType;

    const path = this.pathFor(key);
    await mkdir(dirname(path), { recursive: true });
    await writeFile(path, bytes);

    return { storageKey: key, size: bytes.byteLength, checksum: checksumOf(bytes) };
  }

  async get(key: string): Promise<Uint8Array | null> {
    try {
      const buffer = await readFile(this.pathFor(key));
      return new Uint8Array(buffer);
    } catch {
      // A missing file is a null, not a throw: the catalogue row can outlive
      // the bytes (a restored database, a cleared disk) and the download route
      // has a better message for that than a 500.
      return null;
    }
  }

  async delete(key: string): Promise<void> {
    await rm(this.pathFor(key), { force: true });
  }
}

/**
 * The S3 slot.
 *
 * Declared and not implemented, so `STORAGE_DRIVER=s3` fails loudly at the
 * first upload with a message naming what is missing — rather than silently
 * falling back to the local disk, which is how a production deployment ends up
 * writing student submissions onto an ephemeral container filesystem and
 * discovering it after the first restart.
 */
class UnconfiguredDriver implements StorageDriver {
  constructor(readonly name: string, private readonly reason: string) {}

  isConfigured(): boolean {
    return false;
  }

  async put(): Promise<PutResult> {
    throw new Error(this.reason);
  }
  async get(): Promise<Uint8Array | null> {
    throw new Error(this.reason);
  }
  async delete(): Promise<void> {
    throw new Error(this.reason);
  }
}

export function storageDriver(): StorageDriver {
  const requested = process.env.STORAGE_DRIVER?.trim() || "local";

  if (requested === "local") return new LocalDriver();

  return new UnconfiguredDriver(
    requested,
    `STORAGE_DRIVER is "${requested}", which has no driver yet. Only "local" is implemented.`
  );
}

/** Whether uploads can work at all — surfaced in the UI rather than discovered. */
export function storageAvailable(): boolean {
  return storageDriver().isConfigured();
}
