import { Types } from "mongoose";
import { connectDB } from "@/lib/db";
import { recordAudit } from "@/lib/admin/audit";
import { fail, ok, readJson, withPermission } from "@/lib/admin/ai/api";
import { AiCourseContent, AiCourseContentVersion } from "@/models/AiCourseContent";
import { AI_CONTENT_STATUS_LABELS, type AiContentStatus } from "@/lib/admin/ai/fields";
import { resolveAiSettings } from "@/lib/admin/ai/settings";

/**
 * POST /api/admin/ai/course-content/:id/publish  (spec §30, §33)
 *
 * The one endpoint that can set `status: "published"`, and it needs the
 * separately-granted `publish` permission (§33). The PATCH endpoint refuses the
 * status outright so there is exactly one path here.
 *
 * Requires `confirm: true` in the body. Not ceremony: §30 requires a
 * confirmation naming the college, regulation and version, and a server-side
 * check is what makes that confirmation real rather than a dialog a client could
 * skip.
 */
export async function POST(req: Request, { params }: { params: Promise<{ id: string }> }) {
  return withPermission("ai_course_content.publish", async (admin) => {
    const { id } = await params;
    if (!Types.ObjectId.isValid(id)) return fail("That is not a content id.", 400, { code: "invalid-id" });

    const body = await readJson(req);
    if (body?.confirm !== true) {
      return fail(
        "Publishing must be confirmed. Send confirm: true once the administrator has seen what will be published.",
        400,
        { code: "confirmation-required" }
      );
    }

    await connectDB();

    const row = await AiCourseContent.findById(id).lean();
    if (!row) return fail("That content no longer exists.", 404, { code: "content-not-found" });

    const status = row.status as AiContentStatus;

    if (status === "published") {
      return fail("That content is already published.", 409, { code: "already-published" });
    }

    /**
     * Only approved content may be published (§18's workflow).
     *
     * Deliberately strict: the whole pipeline exists so that no AI-generated
     * material reaches a student without a human approving it (§25, §42), and
     * allowing `generated → published` would make the review states decorative.
     */
    if (status !== "approved") {
      return fail(
        `Content must be approved before it can be published. It is currently ${AI_CONTENT_STATUS_LABELS[status]}.`,
        409,
        { code: "not-approved" }
      );
    }

    if (!row.content) {
      return fail("There is no content to publish.", 409, { code: "empty-content" });
    }

    if (!row.currentVersionId) {
      return fail("That content has no version to publish.", 409, { code: "no-version" });
    }

    const settings = await resolveAiSettings();

    /**
     * Refuse to publish placeholder text.
     *
     * The mock provider marks everything it writes as placeholder, and content
     * produced by it must never reach a student — publishing it would be the
     * worst possible outcome of a convenience meant for local development.
     */
    if (row.provider === "mock") {
      return fail(
        "This content was generated by the mock provider and is placeholder text. Configure a real provider in AI Settings and regenerate before publishing.",
        409,
        { code: "mock-content" }
      );
    }

    const now = new Date();

    // Mark the version immutable *before* the record flips, so a concurrent
    // edit cannot slip in between the two writes.
    await AiCourseContentVersion.updateOne(
      { _id: row.currentVersionId },
      { $set: { published: true } }
    );

    await AiCourseContent.updateOne(
      { _id: row._id },
      {
        $set: {
          status: "published",
          publishedAt: now,
          publishedBy: new Types.ObjectId(admin.id),
          publishedVersionId: row.currentVersionId,
          unpublishedAt: null,
          unpublishedBy: null,
          unpublishReason: null,
          updatedBy: new Types.ObjectId(admin.id),
        },
      }
    );

    const version = await AiCourseContentVersion.findById(row.currentVersionId)
      .select("versionNumber")
      .lean();

    await recordAudit({
      actor: admin,
      action: "ai.content.published",
      entityType: "AiCourseContent",
      entityId: String(row._id),
      entityLabel: row.title,
      before: { status },
      after: { status: "published", versionNumber: version?.versionNumber ?? null },
      metadata: {
        college: row.collegeName,
        program: row.programName,
        branch: row.branchName,
        regulation: row.regulationCode,
        academicYear: row.academicYearLabel,
        semester: row.semester,
        subject: row.subjectName,
        contentType: row.contentType,
        provider: row.provider,
        model: row.model,
        academicallyApproved: row.academicallyApproved === true,
        requireAdminReview: settings.safety.requireAdminReview,
      },
    });

    return ok({
      id: String(row._id),
      status: "published",
      publishedAt: now,
      publishedVersion: version?.versionNumber ?? null,
    });
  });
}
