import { after } from "next/server";
import { fail, ok, readJson, readNumber, readString, readStringArray, withGenerationLimit } from "@/lib/admin/ai/api";
import { requestGeneration, runJob } from "@/lib/admin/ai/generator";

/**
 * POST /api/admin/ai/course-content/generate  (spec §10, §19, §35)
 *
 * Accepts a generation request, returns a job reference, and runs the work
 * *after* the response via `after()`. The browser never waits on a model
 * (§19) — it gets a job id in milliseconds and polls
 * `/api/admin/ai/generation-jobs/:id`.
 *
 * The request carries **ids only**. Any `collegeName`, `subjectName` or
 * `syllabus` in the body is ignored: the backend resolves and re-verifies the
 * whole academic chain from the database (§10, §26), because a caller that could
 * supply its own academic labels could file one college's content under
 * another's regulation.
 */

/**
 * `after` inherits the route's budget, so a generation that outlives the default
 * would be killed halfway through — leaving a job stuck in `processing`. Five
 * minutes comfortably covers the 120s provider timeout plus validation and the
 * version write.
 */
export const maxDuration = 300;

export async function POST(req: Request) {
  return withGenerationLimit("ai_course_content.generate", async (admin) => {
    const body = await readJson(req);
    if (!body) return fail("Send a JSON body.", 400, { code: "invalid-body" });

    const semester = readNumber(body, "semester");
    if (semester === null) {
      return fail("Select a year and semester.", 400, { code: "missing-semester", field: "semester" });
    }

    const options = (body.options ?? {}) as Record<string, unknown>;

    const response = await requestGeneration(
      {
        collegeId: readString(body, "collegeId"),
        programId: readString(body, "programId"),
        branchId: readString(body, "branchId"),
        regulationId: readString(body, "regulationId"),
        academicYearId: readString(body, "academicYearId"),
        semester,
        subjectId: readString(body, "subjectId"),
        contentType: readString(body, "contentType"),
        options: {
          level: typeof options.level === "string" ? options.level : undefined,
          language: typeof options.language === "string" ? options.language : undefined,
          length: typeof options.length === "string" ? options.length : undefined,
          difficulty: typeof options.difficulty === "string" ? options.difficulty : undefined,
          teachingStyles: Array.isArray(options.teachingStyles)
            ? options.teachingStyles.filter((entry): entry is string => typeof entry === "string")
            : undefined,
          instructions: typeof options.instructions === "string" ? options.instructions : null,
          unitNumber: typeof options.unitNumber === "number" ? options.unitNumber : null,
          topicNumber: typeof options.topicNumber === "number" ? options.topicNumber : null,
        },
        sourceMaterialIds: readStringArray(body, "sourceMaterialIds"),
        onDuplicate: ((): "reject" | "new-version" | "replace-draft" => {
          const mode = readString(body, "onDuplicate");
          return mode === "new-version" || mode === "replace-draft" ? mode : "reject";
        })(),
      },
      admin
    );

    if (!response.ok) {
      const { refusal } = response;

      /**
       * 409 for a duplicate, 422 for anything the operator must change.
       *
       * The distinction matters to the UI: a 409 carries `existing` and opens
       * §27's four choices, while a 422 points at a dropdown via `field`.
       */
      const status = refusal.code === "content-exists" || refusal.code === "published-immutable" ? 409 : 422;

      return fail(refusal.message, status, {
        code: refusal.code,
        field: refusal.field,
        details: refusal.existing ? { existing: refusal.existing } : undefined,
      });
    }

    const { accepted } = response;

    // The slow part. Runs after the response is flushed, so a two-minute
    // generation cannot hold the request open.
    after(async () => {
      try {
        await runJob(accepted.jobId);
      } catch (err) {
        // `runJob` records its own failure on the job document; this only
        // catches a fault in that recording, which must not crash the worker.
        console.error(`[ai] job ${accepted.jobReference} could not be run:`, err);
      }
    });

    return ok(
      {
        jobId: accepted.jobId,
        jobReference: accepted.jobReference,
        courseContentId: accepted.courseContentId,
        provider: accepted.provider,
        model: accepted.model,
        /**
         * Surfaced so the screen can say so. Content generated by the mock is
         * placeholder text, and an operator who did not know that could send it
         * to review as if it were real (§42).
         */
        usingMock: accepted.usingMock,
        status: "queued",
      },
      202
    );
  });
}
