import type {
  AIProvider,
  ProviderMessage,
  ProviderOptions,
  ProviderResult,
} from "@/lib/admin/ai/provider";
import type { TutorAnswer } from "@/lib/tutor/schema";

/**
 * The tutor's mock provider — the default when no key is configured (§75).
 *
 * Not lorem ipsum. It reads the topic, the subject and the question back out of
 * the prompt it was handed and builds a **schema-valid** answer from them, so
 * the whole pipeline — validation, caching, storage, progress, the streaming
 * transport, the history list — is exercised end to end before any provider key
 * exists. A stub returning fixed text would make every one of those stages
 * untested until the day a key arrives.
 *
 * Separate from `admin/ai/providers/mock.ts` rather than an extension of it.
 * That one parses a course-content prompt and emits a course-content document;
 * handed a tutor prompt it would emit valid JSON of the wrong shape, fail
 * validation twice and land on the fallback answer — a failure that looks like
 * a bug in the tutor rather than the wrong mock being used.
 *
 * Every passage says it is placeholder text. §36 forbids passing generated
 * material off as authoritative, and mock content that read like a real
 * explanation would eventually be quoted by a student in an exam.
 */
export class MockTutorProvider implements AIProvider {
  readonly type = "mock" as const;
  readonly name = "Mock tutor";

  isConfigured(): boolean {
    return true;
  }

  async validate(): Promise<{ ok: boolean; message: string }> {
    return { ok: true, message: "The mock tutor needs no configuration." };
  }

  async generate(messages: ProviderMessage, options: ProviderOptions): Promise<ProviderResult> {
    return this.generateStructured(messages, options);
  }

  async generateStructured(
    messages: ProviderMessage,
    options: ProviderOptions
  ): Promise<ProviderResult> {
    const started = Date.now();
    await sleep(300);

    const text = JSON.stringify(this.answer(messages));
    return this.result(text, messages, options, started);
  }

  /**
   * A real stream, chunked mid-sentence.
   *
   * Emitting the whole payload as one delta would let a client that only
   * happens to work on complete JSON pass locally and break against a real
   * provider. Splitting on a fixed width guarantees the boundaries land inside
   * tokens, strings and escapes, which is the case the client has to survive.
   */
  async *stream(
    messages: ProviderMessage,
    options: ProviderOptions
  ): AsyncIterable<{ delta: string; done: boolean }> {
    const text = JSON.stringify(this.answer(messages));

    // Honoured so the streaming path is exercised against the same budget a
    // real provider gets: a client that only works when the whole answer
    // arrives would otherwise pass here and fail against a truncating model.
    const limit = Math.min(text.length, options.maxTokens * 4);

    for (let index = 0; index < limit; index += 24) {
      await sleep(18);
      yield { delta: text.slice(index, index + 24), done: false };
    }

    yield { delta: "", done: true };
  }

  private answer(messages: ProviderMessage): TutorAnswer {
    const topic = field(messages.system, "CURRENT TOPIC") ?? "this topic";
    const subject = field(messages.system, "Subject") ?? "this subject";
    const depth = (field(messages.system, "REQUESTED DEPTH") ?? "Basic").toLowerCase();
    const question = messages.user.split("\n").at(-1)?.trim() || `Explain ${topic}`;

    const level = (
      ["basic", "practical", "intermediate", "advanced", "expert"].includes(depth)
        ? depth
        : "basic"
    ) as TutorAnswer["depthLevel"];

    return {
      title: `${topic} — placeholder answer`,
      summary: `This is placeholder text from EduPilot's mock tutor. No AI provider is configured, so nothing here was generated by a model.`,
      explanation: [
        `**This answer is placeholder text.** EduPilot has no AI provider configured, so the mock tutor answered instead of a model.`,
        ``,
        `The question that was asked, against **${topic}** in **${subject}**, at the *${level}* level:`,
        ``,
        `> ${question}`,
        ``,
        `A configured provider would answer it here, grounded on the syllabus unit shown on this page. To enable one, set the provider environment variables described in \`.env.example\` and enable it in Admin → AI & Learning → AI Settings.`,
        ``,
        `Nothing on this screen above the tutor panel is placeholder text — the syllabus and the prepared explanation come from your college's curriculum.`,
      ].join("\n"),
      practicalExample: `A worked example of ${topic} would appear here.`,
      code: null,
      codeLanguage: null,
      keyPoints: [
        "This answer came from the mock tutor, not from an AI model.",
        `The request was routed with the topic "${topic}" and its syllabus unit attached.`,
        "Configure a provider to get real answers.",
      ],
      commonMistakes: [],
      relatedConcepts: [],
      nextTopics: [],
      difficulty: "moderate",
      depthLevel: level,
      offTopicNote: null,
    };
  }

  private result(
    text: string,
    messages: ProviderMessage,
    options: ProviderOptions,
    started: number
  ): ProviderResult {
    // Roughly four characters per token. Approximate on purpose: it exists so
    // the usage dashboard has non-zero numbers to render in development, and a
    // real tokenizer here would be precision nobody acts on.
    const promptTokens = Math.ceil((messages.system.length + messages.user.length) / 4);
    const completionTokens = Math.ceil(text.length / 4);

    return {
      text,
      usage: {
        promptTokens,
        completionTokens,
        totalTokens: promptTokens + completionTokens,
      },
      model: options.model || "mock-tutor-1",
      durationMs: Date.now() - started,
    };
  }
}

/** Pull `Label: value` out of the rendered prompt. */
function field(system: string, label: string): string | null {
  const match = system.match(new RegExp(`^${escapeRegExp(label)}:\\s*(.+)$`, "m"));
  return match?.[1]?.trim() || null;
}

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}
