import { Types } from "mongoose";
import { connectDB } from "@/lib/db";
import { AiProviderConfig, type AiProviderConfigDoc } from "@/models/AiCourseContent";
import { AI_PROVIDER_TYPE_LABELS, type AiProviderType } from "@/lib/admin/ai/fields";
import type { AIProvider } from "@/lib/admin/ai/provider";
import { GeminiProvider, GEMINI_DEFAULT_MODEL } from "@/lib/admin/ai/providers/gemini";
import { MockProvider } from "@/lib/admin/ai/providers/mock";
import { VertexAIProvider, VERTEX_DEFAULT_MODEL } from "@/lib/admin/ai/providers/vertex";
import {
  OPENAI_COMPATIBLE_SERVICES,
  OpenAICompatibleProvider,
} from "@/lib/admin/ai/providers/openai-compatible";

/**
 * Provider selection and generation settings (spec §23, §24).
 *
 * The backend decides which provider runs — never the caller (§23). A request
 * carries what to generate and how, never who should generate it, so a client
 * cannot route around a disabled provider or a lower temperature.
 *
 * Selection order:
 *   1. the enabled config marked `isDefault`
 *   2. any enabled config whose provider is actually configured
 *   3. the mock
 *
 * Falling back to the mock rather than failing is deliberate: a deployment with
 * no key should still be able to walk the whole flow (§45 phase 1), and a job
 * that says "generated by mock" is far easier to diagnose than one that says
 * "provider unavailable".
 */

const PROVIDERS: Record<AiProviderType, () => AIProvider> = {
  mock: () => new MockProvider(),
  /**
   * Vertex and Gemini call the same models over the same wire format and share
   * `gemini-core.ts`; they are separate entries because they authenticate,
   * bill and fail differently.
   */
  vertex: () => new VertexAIProvider(),
  gemini: () => new GeminiProvider(),
  /**
   * Three services, one class. They differ only in a base URL, a key variable
   * and a default model, which `OPENAI_COMPATIBLE_SERVICES` holds as data.
   */
  deepseek: () => new OpenAICompatibleProvider(OPENAI_COMPATIBLE_SERVICES.deepseek),
  groq: () => new OpenAICompatibleProvider(OPENAI_COMPATIBLE_SERVICES.groq),
  openai: () => new OpenAICompatibleProvider(OPENAI_COMPATIBLE_SERVICES.openai),
  "openai-compatible": () =>
    new OpenAICompatibleProvider(OPENAI_COMPATIBLE_SERVICES["openai-compatible"]),
  /**
   * Ollama speaks the same protocol but needs no key, so it cannot reuse the
   * class above unchanged — `isConfigured` would refuse a correctly-configured
   * local server. Still a slot, so the settings screen can show it as
   * unavailable rather than imply the abstraction has only the implementations
   * that happen to be finished.
   */
  ollama: () => new MockProvider(),
  anthropic: () => new MockProvider(),
};

/** Which provider types have a real implementation today (§45). */
export const IMPLEMENTED_PROVIDERS: AiProviderType[] = [
  "mock",
  "vertex",
  "gemini",
  "deepseek",
  "groq",
  "openai",
  "openai-compatible",
];

export function providerFor(type: AiProviderType): AIProvider {
  return (PROVIDERS[type] ?? PROVIDERS.mock)();
}

export type ResolvedAiSettings = {
  provider: AIProvider;
  providerType: AiProviderType;
  model: string;
  temperature: number;
  maxTokens: number;
  topP: number;
  timeoutMs: number;
  defaults: {
    level: string;
    language: string;
    length: string;
    difficulty: string;
  };
  safety: {
    enableContentValidation: boolean;
    enableHallucinationChecks: boolean;
    requireAdminReview: boolean;
    preventAutomaticPublishing: boolean;
  };
  /** The config document backing this, when there is one. */
  configId: string | null;
  /** Set when the requested provider was unusable and the mock stood in. */
  fellBackFrom: AiProviderType | null;
};

/**
 * How long a single generation may take.
 *
 * Not configurable per config document: it has to stay inside the platform's own
 * request budget, and an operator raising it to ten minutes would make the job
 * runner look hung rather than make generation succeed. Long work is handled by
 * generating one unit at a time (§28), not by waiting longer.
 */
const TIMEOUT_MS = 120_000;

const FALLBACK: Omit<ResolvedAiSettings, "provider"> = {
  providerType: "mock",
  model: "mock-1",
  temperature: 0.4,
  maxTokens: 8192,
  topP: 0.95,
  timeoutMs: TIMEOUT_MS,
  defaults: { level: "undergraduate", language: "english", length: "standard", difficulty: "moderate" },
  safety: {
    enableContentValidation: true,
    enableHallucinationChecks: true,
    requireAdminReview: true,
    preventAutomaticPublishing: true,
  },
  configId: null,
  fellBackFrom: null,
};

export async function resolveAiSettings(): Promise<ResolvedAiSettings> {
  await connectDB();

  const configs = await AiProviderConfig.find({ enabled: true })
    .sort({ isDefault: -1, updatedAt: -1 })
    .lean();

  for (const config of configs) {
    const type = config.providerType as AiProviderType;
    const provider = providerFor(type);

    // An enabled Gemini config with no key on the server is a misconfiguration,
    // not a reason to refuse the request. Note the fallback so the job and the
    // settings screen can both say what happened.
    if (!IMPLEMENTED_PROVIDERS.includes(type) || !provider.isConfigured()) continue;

    return {
      provider,
      providerType: type,
      model: config.model || defaultModelFor(type),
      temperature: config.temperature ?? FALLBACK.temperature,
      maxTokens: config.maxTokens ?? FALLBACK.maxTokens,
      topP: config.topP ?? FALLBACK.topP,
      timeoutMs: TIMEOUT_MS,
      defaults: {
        level: config.defaultLevel ?? FALLBACK.defaults.level,
        language: config.defaultLanguage ?? FALLBACK.defaults.language,
        length: config.defaultLength ?? FALLBACK.defaults.length,
        difficulty: config.defaultDifficulty ?? FALLBACK.defaults.difficulty,
      },
      safety: {
        enableContentValidation: config.enableContentValidation !== false,
        enableHallucinationChecks: config.enableHallucinationChecks !== false,
        requireAdminReview: config.requireAdminReview !== false,
        preventAutomaticPublishing: config.preventAutomaticPublishing !== false,
      },
      configId: String(config._id),
      fellBackFrom: null,
    };
  }

  const requested = configs[0]?.providerType as AiProviderType | undefined;
  return {
    ...FALLBACK,
    provider: providerFor("mock"),
    fellBackFrom: requested && requested !== "mock" ? requested : null,
  };
}

export function defaultModelFor(type: AiProviderType): string {
  if (type === "vertex") return VERTEX_DEFAULT_MODEL;
  if (type === "gemini") return GEMINI_DEFAULT_MODEL;
  if (type === "ollama") return "llama3.1";
  if (type === "mock") return "mock-1";
  return OPENAI_COMPATIBLE_SERVICES[type]?.defaultModel ?? "";
}

/**
 * Ensure a provider config row exists, so AI Settings is never an empty screen.
 *
 * Creates the mock as the enabled default on first read. Gemini is created
 * *disabled*: enabling a provider is an operator decision with a cost attached,
 * and doing it automatically because a key happened to be present would start
 * spending money without anyone choosing to.
 */
export async function ensureProviderConfigs(): Promise<(AiProviderConfigDoc & { _id: Types.ObjectId })[]> {
  await connectDB();

  /**
   * Backfill a row per implemented provider, rather than seeding only an empty
   * collection.
   *
   * The seed-once version left every existing deployment unable to see a
   * provider added after its first run: `vertex` shipped, the code supported it,
   * and the settings screen — which renders from these documents — had no row to
   * show. The only way to enable it was a manual database edit, which is exactly
   * the kind of step that gets done on one environment and forgotten on the
   * next.
   *
   * Inserting is all this does. An existing row keeps its `enabled`, `isDefault`
   * and tuning untouched, so a backfill can never switch a provider on, change
   * which one is default, or start spending money.
   */
  const rows = await AiProviderConfig.find({}).select("providerType").lean();
  const present = new Set(rows.map((row) => String(row.providerType)));

  const wanted: {
    providerType: AiProviderType;
    model: string;
    configuration?: Record<string, unknown>;
  }[] = [
    { providerType: "mock", model: "mock-1" },
    { providerType: "vertex", model: VERTEX_DEFAULT_MODEL },
    {
      providerType: "gemini",
      model: GEMINI_DEFAULT_MODEL,
      configuration: { endpoint: "https://generativelanguage.googleapis.com/v1beta" },
    },
  ];

  const missing = wanted.filter((entry) => !present.has(entry.providerType));

  if (missing.length) {
    await AiProviderConfig.create(
      missing.map((entry) => ({
        providerName: AI_PROVIDER_TYPE_LABELS[entry.providerType],
        providerType: entry.providerType,
        model: entry.model,
        /**
         * Everything arrives **off**, including the mock, unless this is the
         * very first run and there is nothing else to fall back to. A provider
         * that enabled itself on deploy would start calling a paid API because
         * someone shipped a release.
         */
        enabled: rows.length === 0 && entry.providerType === "mock",
        isDefault: rows.length === 0 && entry.providerType === "mock",
        temperature: 0.4,
        ...(entry.configuration ? { configuration: entry.configuration } : {}),
      }))
    );
  }

  return AiProviderConfig.find({}).sort({ isDefault: -1, providerType: 1 }).lean() as Promise<
    (AiProviderConfigDoc & { _id: Types.ObjectId })[]
  >;
}

/**
 * Record what a call cost, for §24's monitoring.
 *
 * Counters on the config document rather than a separate metrics collection:
 * the numbers wanted are totals per provider, an increment is atomic, and a
 * time series is a different feature from the one asked for.
 */
export async function recordUsage(input: {
  configId: string | null;
  tokens: number;
  durationMs: number;
  failed: boolean;
}): Promise<void> {
  if (!input.configId) return;

  try {
    await AiProviderConfig.updateOne(
      { _id: input.configId },
      {
        $inc: {
          requestCount: 1,
          failedCount: input.failed ? 1 : 0,
          totalTokens: input.tokens,
          totalDurationMs: input.durationMs,
        },
      }
    );
  } catch (err) {
    // Usage accounting must never be the reason a generation fails.
    console.error("[ai] could not record provider usage:", err);
  }
}
