import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { Types } from "mongoose";
import { connectDB } from "@/lib/db";
import { Badge, Card, InfoNote, PageHeader } from "@/components/admin/ui";
import { ContentWorkspace } from "@/components/admin/ai/content-workspace";
import { StatusBadge } from "@/app/admin/(shell)/ai/course-content/page";
import { can, requirePermission } from "@/lib/admin/current-admin";
import { formatRelative } from "@/lib/admin/format";
import { AdminUser } from "@/models/AdminUser";
import { AiCourseContent, AiCourseContentVersion } from "@/models/AiCourseContent";
import { CurriculumSubject } from "@/models/Curriculum";
import { contentTypeLabel, type AiContentStatus } from "@/lib/admin/ai/fields";
import { editBlockedReason } from "@/lib/admin/ai/repository";

export const metadata: Metadata = { title: "AI Course Content" };

/**
 * One piece of generated content: review it, move it through the workflow,
 * inspect versions, preview it as a student would see it, and publish it
 * (spec §14, §17, §29, §30).
 *
 * The heavy reading happens here on the server — content, versions, the
 * subject's syllabus — and the interactive shell is a single client island. A
 * generated course is large, and shipping it twice (once as HTML, once as a
 * client payload) would be the biggest cost on the page.
 */
export default async function ContentDetailPage(props: { params: Promise<{ id: string }> }) {
  const { id } = await props.params;
  if (!Types.ObjectId.isValid(id)) notFound();

  const admin = await requirePermission("ai_course_content.view", `/admin/ai/course-content/${id}`);

  await connectDB();

  const row = await AiCourseContent.findById(id).lean();
  if (!row) notFound();

  const [versions, subject, actors] = await Promise.all([
    AiCourseContentVersion.find({ courseContentId: row._id })
      .sort({ versionNumber: -1 })
      .limit(50)
      .select("versionNumber origin note createdAt createdBy provider model published tokenUsage restoredFromVersion")
      .lean(),
    /**
     * The syllabus is loaded so the preview can show what the content was
     * *supposed* to cover next to what it does. A unit the content skipped is
     * only visible if the outline it was grounded on is on the page too.
     */
    CurriculumSubject.findById(row.subjectId).select("name code units learningObjectives").lean(),
    AdminUser.find({
      _id: { $in: [row.createdBy, row.approvedBy, row.publishedBy, row.reviewedBy].filter(Boolean) },
    })
      .select("name")
      .lean(),
  ]);

  const names = new Map(actors.map((actor) => [String(actor._id), actor.name]));
  const status = row.status as AiContentStatus;

  const versionAuthorIds = [...new Set(versions.map((version) => version.createdBy).filter(Boolean).map(String))];
  const versionAuthors = await AdminUser.find({ _id: { $in: versionAuthorIds } }).select("name").lean();
  const versionNames = new Map(versionAuthors.map((author) => [String(author._id), author.name]));

  return (
    <div className="mx-auto max-w-[1500px]">
      <PageHeader
        title={row.subjectName ?? row.title}
        description={`${contentTypeLabel(row.contentType)} · ${row.collegeName ?? ""}`}
        breadcrumbs={[
          { label: "AI & Learning" },
          { label: "AI Content Library", href: "/admin/ai/content-library" },
          { label: row.subjectName ?? row.title },
        ]}
        meta={
          <span className="flex flex-wrap items-center gap-1.5">
            <StatusBadge status={status} />
            <Badge tone="neutral">v{row.versionCount ?? 0}</Badge>
            {row.provider === "mock" && <Badge tone="warning">placeholder</Badge>}
            {row.academicallyApproved && <Badge tone="info">marked reviewed</Badge>}
          </span>
        }
      />

      {/*
        The single most important disclaimer in the module (§42).

        Shown unless a human has explicitly marked the content as academically
        checked. Nothing generated is university-approved, and the page must not
        let a reader assume otherwise.
      */}
      {!row.academicallyApproved && (
        <div className="mb-3">
          <InfoNote tone={row.provider === "mock" ? "warning" : "neutral"}>
            {row.provider === "mock" ? (
              <>
                <strong className="font-semibold">Placeholder content.</strong> Generated by the mock
                provider, not a real model. It cannot be published — enable a provider in AI Settings and
                regenerate.
              </>
            ) : (
              <>
                AI-generated and <strong className="font-semibold">not approved academic material</strong>.
                It is not endorsed by {row.collegeName ?? "the college"} or any university, and must be
                reviewed by an academic administrator before it reaches a student.
              </>
            )}
          </InfoNote>
        </div>
      )}

      {row.lastGenerationError && status !== "generating" && (
        <div className="mb-3">
          <InfoNote tone="warning">
            <strong className="font-semibold">Last generation failed:</strong> {row.lastGenerationError}
          </InfoNote>
        </div>
      )}

      <div className="mb-3 grid gap-3 lg:grid-cols-[1fr_320px]">
        <Card title="Academic Context" description="What this content is mapped to. It cannot be changed after generation.">
          <dl className="grid gap-x-6 gap-y-3 sm:grid-cols-2 lg:grid-cols-3">
            {[
              ["College", row.collegeName],
              ["Program", row.programName],
              ["Branch", row.branchName],
              ["Regulation", row.regulationCode],
              ["Academic Year", row.academicYearLabel],
              ["Year / Semester", `Year ${row.year} · Semester ${row.semester}`],
              ["Subject", row.subjectName],
              ["Subject Code", row.subjectCode],
              ["Content Type", contentTypeLabel(row.contentType)],
            ].map(([label, value]) => (
              <div key={label as string}>
                <dt className="text-[11px] font-medium uppercase tracking-[0.06em] text-slate-400 dark:text-slate-500">
                  {label}
                </dt>
                <dd className="mt-0.5 text-[13px] text-slate-800 dark:text-slate-100">
                  {value || <span className="text-slate-400">—</span>}
                </dd>
              </div>
            ))}
          </dl>
        </Card>

        <Card title="Provenance" description="How this content came to be.">
          <dl className="space-y-2.5">
            {[
              ["Provider", row.provider ? `${row.provider}${row.model ? ` · ${row.model}` : ""}` : "—"],
              ["Created by", row.createdBy ? (names.get(String(row.createdBy)) ?? "—") : "—"],
              ["Reviewed", row.reviewedAt ? formatRelative(row.reviewedAt as Date) : "Not yet"],
              [
                "Approved",
                row.approvedAt
                  ? `${formatRelative(row.approvedAt as Date)}${row.approvedBy ? ` by ${names.get(String(row.approvedBy)) ?? "—"}` : ""}`
                  : "Not yet",
              ],
              [
                "Published",
                row.publishedAt
                  ? `${formatRelative(row.publishedAt as Date)}${row.publishedBy ? ` by ${names.get(String(row.publishedBy)) ?? "—"}` : ""}`
                  : "Not published",
              ],
              ["Last updated", formatRelative(row.updatedAt as Date)],
            ].map(([label, value]) => (
              <div key={label as string} className="flex justify-between gap-3">
                <dt className="text-[12px] text-slate-500 dark:text-slate-400">{label}</dt>
                <dd className="text-right text-[12.5px] text-slate-800 dark:text-slate-100">{value}</dd>
              </div>
            ))}
          </dl>

          {row.unpublishReason && (
            <p className="mt-3 rounded-lg border border-slate-200 bg-slate-50 px-2.5 py-2 text-[12px] text-slate-600 dark:border-slate-700 dark:bg-slate-800/50 dark:text-slate-300">
              <strong className="font-medium">Unpublished:</strong> {row.unpublishReason}
            </p>
          )}
        </Card>
      </div>

      <ContentWorkspace
        contentId={String(row._id)}
        contentType={row.contentType}
        contentTypeLabel={contentTypeLabel(row.contentType)}
        status={status}
        body={row.content ?? null}
        editBlockedReason={editBlockedReason(status)}
        isMock={row.provider === "mock"}
        academicallyApproved={row.academicallyApproved === true}
        syllabusUnits={(subject?.units ?? []).map((unit) => ({
          unitNumber: unit.unitNumber,
          title: unit.title,
        }))}
        versions={versions.map((version) => ({
          id: String(version._id),
          versionNumber: version.versionNumber,
          origin: version.origin,
          note: version.note ?? null,
          createdAt: (version.createdAt as Date).toISOString(),
          createdBy: version.createdBy ? (versionNames.get(String(version.createdBy)) ?? null) : null,
          provider: version.provider ?? null,
          model: version.model ?? null,
          published: version.published === true,
          totalTokens: version.tokenUsage?.totalTokens ?? null,
          restoredFromVersion: version.restoredFromVersion ?? null,
        }))}
        permissions={{
          edit: can(admin, "ai_course_content.edit"),
          review: can(admin, "ai_course_content.review"),
          publish: can(admin, "ai_course_content.publish"),
        }}
      />
    </div>
  );
}
